name: oneuldo_mobile
description: 오늘도요 (今日もね) - 어르신 음성 AI 대화 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2        # AI 음성 TTS
  http: ^1.2.1               # HTTP 통신
  shared_preferences: ^2.2.3 # 로컬 저장 (elderId, language)
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
